In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

# Tüm sütunları göster
pd.set_option('display.max_columns', None)

# Tüm satırları göster
pd.set_option('display.max_rows', None)

# Sütun genişliğini sınırlandırma
pd.set_option('display.max_colwidth', None)

# Tablo genişliğini otomatik ayarla
pd.set_option('display.width', None)

In [ ]:

import pandas as pd
import numpy as np
yol =  "/content/drive/MyDrive/data/ham_veri.csv"
df =pd.read_csv(yol)
df.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,54865,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,55054,109,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,55055,52,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,46236,34,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,54863,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [ ]:
df.shape[0]

2830743

In [ ]:
df.columns = df.columns.str.replace(" ","")
df.columns

Index(['DestinationPort', 'FlowDuration', 'TotalFwdPackets',
       'TotalBackwardPackets', 'TotalLengthofFwdPackets',
       'TotalLengthofBwdPackets', 'FwdPacketLengthMax', 'FwdPacketLengthMin',
       'FwdPacketLengthMean', 'FwdPacketLengthStd', 'BwdPacketLengthMax',
       'BwdPacketLengthMin', 'BwdPacketLengthMean', 'BwdPacketLengthStd',
       'FlowBytes/s', 'FlowPackets/s', 'FlowIATMean', 'FlowIATStd',
       'FlowIATMax', 'FlowIATMin', 'FwdIATTotal', 'FwdIATMean', 'FwdIATStd',
       'FwdIATMax', 'FwdIATMin', 'BwdIATTotal', 'BwdIATMean', 'BwdIATStd',
       'BwdIATMax', 'BwdIATMin', 'FwdPSHFlags', 'BwdPSHFlags', 'FwdURGFlags',
       'BwdURGFlags', 'FwdHeaderLength', 'BwdHeaderLength', 'FwdPackets/s',
       'BwdPackets/s', 'MinPacketLength', 'MaxPacketLength',
       'PacketLengthMean', 'PacketLengthStd', 'PacketLengthVariance',
       'FINFlagCount', 'SYNFlagCount', 'RSTFlagCount', 'PSHFlagCount',
       'ACKFlagCount', 'URGFlagCount', 'CWEFlagCount', 'ECEFlagCount',
       'Down/UpRatio', 'AveragePacketSize', 'AvgFwdSegmentSize',
       'AvgBwdSegmentSize', 'FwdHeaderLength.1', 'FwdAvgBytes/Bulk',
       'FwdAvgPackets/Bulk', 'FwdAvgBulkRate', 'BwdAvgBytes/Bulk',
       'BwdAvgPackets/Bulk', 'BwdAvgBulkRate', 'SubflowFwdPackets',
       'SubflowFwdBytes', 'SubflowBwdPackets', 'SubflowBwdBytes',
       'Init_Win_bytes_forward', 'Init_Win_bytes_backward', 'act_data_pkt_fwd',
       'min_seg_size_forward', 'ActiveMean', 'ActiveStd', 'ActiveMax',
       'ActiveMin', 'IdleMean', 'IdleStd', 'IdleMax', 'IdleMin', 'Label'],
      dtype='object')

In [ ]:
number_df = df.drop(columns="Label")
print(f"inf satır sayısı:{np.isinf(number_df).sum().sum()}")
print(f"NaN satır sayısı:{df.isna().sum().sum()}")
print(f"tekrar eden satır sayısı:{df.duplicated().sum()}")
print(f"satır sayısı:{df.shape[0]}")

inf satır sayısı:4376
NaN satır sayısı:1358
tekrar eden satır sayısı:308381
satır sayısı:2830743

In [ ]:
df.replace([np.inf,-np.inf],np.nan,inplace=True)
df.isna().sum()

DestinationPort               0
FlowDuration                  0
TotalFwdPackets               0
TotalBackwardPackets          0
TotalLengthofFwdPackets       0
TotalLengthofBwdPackets       0
FwdPacketLengthMax            0
FwdPacketLengthMin            0
FwdPacketLengthMean           0
FwdPacketLengthStd            0
BwdPacketLengthMax            0
BwdPacketLengthMin            0
BwdPacketLengthMean           0
BwdPacketLengthStd            0
FlowBytes/s                2867
FlowPackets/s              2867
FlowIATMean                   0
FlowIATStd                    0
FlowIATMax                    0
FlowIATMin                    0
FwdIATTotal                   0
FwdIATMean                    0
FwdIATStd                     0
FwdIATMax                     0
FwdIATMin                     0
BwdIATTotal                   0
BwdIATMean                    0
BwdIATStd                     0
BwdIATMax                     0
BwdIATMin                     0
FwdPSHFlags                   0
BwdPSHFlags                   0
FwdURGFlags                   0
BwdURGFlags                   0
FwdHeaderLength               0
BwdHeaderLength               0
FwdPackets/s                  0
BwdPackets/s                  0
MinPacketLength               0
MaxPacketLength               0
PacketLengthMean              0
PacketLengthStd               0
PacketLengthVariance          0
FINFlagCount                  0
SYNFlagCount                  0
RSTFlagCount                  0
PSHFlagCount                  0
ACKFlagCount                  0
URGFlagCount                  0
CWEFlagCount                  0
ECEFlagCount                  0
Down/UpRatio                  0
AveragePacketSize             0
AvgFwdSegmentSize             0
AvgBwdSegmentSize             0
FwdHeaderLength.1             0
FwdAvgBytes/Bulk              0
FwdAvgPackets/Bulk            0
FwdAvgBulkRate                0
BwdAvgBytes/Bulk              0
BwdAvgPackets/Bulk            0
BwdAvgBulkRate                0
SubflowFwdPackets             0
SubflowFwdBytes               0
SubflowBwdPackets             0
SubflowBwdBytes               0
Init_Win_bytes_forward        0
Init_Win_bytes_backward       0
act_data_pkt_fwd              0
min_seg_size_forward          0
ActiveMean                    0
ActiveStd                     0
ActiveMax                     0
ActiveMin                     0
IdleMean                      0
IdleStd                       0
IdleMax                       0
IdleMin                       0
Label                         0
dtype: int64

In [ ]:
np.isinf(df.drop(columns="Label")).sum().sum()

np.int64(0)

In [ ]:
df.isna().sum().sum()

np.int64(5734)

In [ ]:
df=df.fillna(df.mean(numeric_only=True))
print(f"nan degerler ort ile dolduruldu \nnan sayisi:{df.isna().sum().sum()}")

nan degerler ort ile dolduruldu
nan sayisi:0

In [ ]:
print(f"tekrar eden satır sayısı:{df.duplicated().sum()}")
print(f"tekrar eden satırların temizlenmesinden onceki satir sayisi:{df.shape[0]}")
df=df.drop_duplicates()
print(f"tekrar eden satır sayısı:{df.duplicated().sum()}")
print(f"tekrar eden satırların temizlenmesinden sonraki satir sayisi:{df.shape[0]}")

tekrar eden satır sayısı:308381
tekrar eden satırların temizlenmesinden onceki satir sayisi:2830743
tekrar eden satır sayısı:0
tekrar eden satırların temizlenmesinden sonraki satir sayisi:2522362

In [ ]:
import numpy as np
import pandas as pd

# 1) Label'ı çıkar
df_clean = df.drop(columns="Label")

# 2) inf değerleri temizle
df_clean = df_clean.replace([np.inf, -np.inf], np.nan)

# 3) NaN varsa temizle (isteğe bağlı ama önerilir)
df_clean = df_clean.dropna()

# 4) sadece sayısal sütunlar
numeric_df = df_clean.select_dtypes(include=["number"])

# 5) variance hesapla
variances = numeric_df.var()

# 6) variance = 0 olan feature'lar
zero_var_cols = variances[variances == 0].index

# 7) çıkarılan feature'ları yazdır
print("Silinen feature'lar (variance = 0):")
for col in zero_var_cols:
    print("-", col)

# 8) dataset'ten çıkar
df_clean = df_clean.drop(columns=zero_var_cols)

print("\nYeni dataset shape:", df_clean.shape)

Silinen feature'lar (variance = 0):
- BwdPSHFlags
- BwdURGFlags
- FwdAvgBytes/Bulk
- FwdAvgPackets/Bulk
- FwdAvgBulkRate
- BwdAvgBytes/Bulk
- BwdAvgPackets/Bulk
- BwdAvgBulkRate

Yeni dataset shape: (2522362, 70)

In [ ]:
df_final = df_clean.copy()
df_final["Label"] = df["Label"]

In [ ]:
corr_matrix = df_final.corr(numeric_only=True)
print(corr_matrix)

                         DestinationPort  FlowDuration  TotalFwdPackets  \
DestinationPort                 1.000000     -0.171828        -0.004652
FlowDuration                   -0.171828      1.000000         0.020571
TotalFwdPackets                -0.004652      0.020571         1.000000
TotalBackwardPackets           -0.004356      0.019389         0.999070
TotalLengthofFwdPackets         0.009611      0.063509         0.365510
TotalLengthofBwdPackets        -0.003388      0.015998         0.996993
FwdPacketLengthMax              0.090989      0.263401         0.009071
FwdPacketLengthMin             -0.047160     -0.115716        -0.003255
FwdPacketLengthMean             0.136916      0.134033        -0.000262
FwdPacketLengthStd              0.123060      0.224957         0.001110
BwdPacketLengthMax             -0.212699      0.485858         0.022552
BwdPacketLengthMin             -0.262417     -0.238692        -0.006068
BwdPacketLengthMean            -0.238842      0.448503         0.021123
BwdPacketLengthStd             -0.190515      0.433671         0.006045
FlowBytes/s                     0.070222     -0.024981         0.000391
FlowPackets/s                   0.359279     -0.109926        -0.002342
FlowIATMean                    -0.113636      0.534831        -0.001366
FlowIATStd                     -0.131931      0.734884        -0.000954
FlowIATMax                     -0.130869      0.779979         0.001862
FlowIATMin                     -0.023383      0.060566        -0.000589
FwdIATTotal                    -0.171004      0.998529         0.020240
FwdIATMean                     -0.107032      0.543119        -0.001361
FwdIATStd                      -0.111044      0.721063        -0.000333
FwdIATMax                      -0.129597      0.779716         0.001418
FwdIATMin                      -0.055521      0.209850        -0.001290
BwdIATTotal                    -0.119856      0.819887         0.023794
BwdIATMean                     -0.075871      0.408650        -0.000883
BwdIATStd                      -0.041670      0.517722         0.000475
BwdIATMax                      -0.061670      0.580336         0.003095
BwdIATMin                      -0.055113      0.212795        -0.001144
FwdPSHFlags                     0.234993     -0.017047         0.001882
FwdURGFlags                     0.004445     -0.002651        -0.000059
FwdHeaderLength                 0.000457     -0.000097         0.000476
BwdHeaderLength                 0.000761     -0.001049         0.013750
FwdPackets/s                    0.348251     -0.099488        -0.002132
BwdPackets/s                    0.143760     -0.080348        -0.001655
MinPacketLength                -0.255221     -0.247385        -0.006792
MaxPacketLength                -0.143499      0.501514         0.021735
PacketLengthMean               -0.171428      0.417241         0.024239
PacketLengthStd                -0.139519      0.445197         0.011654
PacketLengthVariance           -0.077536      0.271962         0.005141
FINFlagCount                   -0.036841      0.217883        -0.001337
SYNFlagCount                    0.234993     -0.017047         0.001882
RSTFlagCount                   -0.007134      0.008075         0.000339
PSHFlagCount                   -0.217887      0.179773         0.007061
ACKFlagCount                    0.585195      0.033256         0.001378
URGFlagCount                    0.523381     -0.117224        -0.003794
CWEFlagCount                    0.004445     -0.002651        -0.000059
ECEFlagCount                   -0.007044      0.008023         0.000337
Down/UpRatio                    0.027562     -0.165840         0.000882
AveragePacketSize              -0.172832      0.394800         0.021865
AvgFwdSegmentSize               0.136916      0.134033        -0.000262
AvgBwdSegmentSize              -0.238842      0.448503         0.021123
FwdHeaderLength.1               0.000457     -0.000097         0.000476
SubflowFwdPackets              -0.004652      0.020571         1.000000
SubflowFwdBytes                 0.009624      0.063592         0.365992
SubflowBwdPackets              -0.004356      0.019389         0.999070
SubflowBwdBytes                -0.003388      0.015998         0.996987
Init_Win_bytes_forward         -0.133049      0.094089         0.003729
Init_Win_bytes_backward         0.206231     -0.034352        -0.000658
act_data_pkt_fwd               -0.003543      0.015728         0.887386
min_seg_size_forward            0.001003     -0.001236        -0.000181
ActiveMean                     -0.040678      0.184985         0.039822
ActiveStd                      -0.048227      0.238497         0.008207
ActiveMax                      -0.058142      0.289933         0.030318
ActiveMin                      -0.027193      0.117259         0.041186
IdleMean                       -0.127989      0.764124         0.001402
IdleStd                         0.006732      0.240369         0.000676
IdleMax                        -0.123677      0.775744         0.001483
IdleMin                        -0.129539      0.734123         0.001266

                         TotalBackwardPackets  TotalLengthofFwdPackets  \
DestinationPort                     -0.004356                 0.009611
FlowDuration                         0.019389                 0.063509
TotalFwdPackets                      0.999070                 0.365510
TotalBackwardPackets                 1.000000                 0.359457
TotalLengthofFwdPackets              0.359457                 1.000000
TotalLengthofBwdPackets              0.994430                 0.353781
FwdPacketLengthMax                   0.008764                 0.196242
FwdPacketLengthMin                  -0.002834                -0.001737
FwdPacketLengthMean                 -0.000617                 0.185073
FwdPacketLengthStd                   0.000743                 0.158876
BwdPacketLengthMax                   0.022342                 0.020773
BwdPacketLengthMin                  -0.005343                -0.027818
BwdPacketLengthMean                  0.021244                 0.016485
BwdPacketLengthStd                   0.005722                 0.007706
FlowBytes/s                          0.000335                 0.002270
FlowPackets/s                       -0.002384                -0.011867
FlowIATMean                         -0.001711                 0.002748
FlowIATStd                          -0.001426                 0.012694
FlowIATMax                           0.001406                 0.024882
FlowIATMin                          -0.000615                -0.003042
FwdIATTotal                          0.019040                 0.062692
FwdIATMean                          -0.001541                 0.004294
FwdIATStd                           -0.000860                 0.021239
FwdIATMax                            0.000947                 0.024958
FwdIATMin                           -0.001160                -0.006131
BwdIATTotal                          0.023219                 0.076069
BwdIATMean                          -0.001039                 0.006502
BwdIATStd                            0.000272                 0.035046
BwdIATMax                            0.003177                 0.040385
BwdIATMin                           -0.001100                -0.005122
FwdPSHFlags                          0.001673                 0.008673
FwdURGFlags                         -0.000061                -0.000325
FwdHeaderLength                      0.000757                -0.001338
BwdHeaderLength                      0.013766                 0.005022
FwdPackets/s                        -0.002231                -0.010602
BwdPackets/s                        -0.001369                -0.009385
MinPacketLength                     -0.006152                -0.028487
MaxPacketLength                      0.021469                 0.074798
PacketLengthMean                     0.024655                 0.081365
PacketLengthStd                      0.011508                 0.057367
PacketLengthVariance                 0.005111                 0.033850
FINFlagCount                        -0.001183                -0.005847
SYNFlagCount                         0.001673                 0.008673
RSTFlagCount                         0.000214                 0.004463
PSHFlagCount                         0.006490                 0.044617
ACKFlagCount                         0.001203                -0.003564
URGFlagCount                        -0.003151                -0.005145
CWEFlagCount                        -0.000061                -0.000325
ECEFlagCount                         0.000213                 0.004452
Down/UpRatio                         0.003279                -0.011819
AveragePacketSize                    0.022290                 0.076025
AvgFwdSegmentSize                   -0.000617                 0.185073
AvgBwdSegmentSize                    0.021244                 0.016485
FwdHeaderLength.1                    0.000757                -0.001338
SubflowFwdPackets                    0.999070                 0.365510
SubflowFwdBytes                      0.359939                 0.999999
SubflowBwdPackets                    1.000000                 0.359457
SubflowBwdBytes                      0.994424                 0.353788
Init_Win_bytes_forward               0.003167                 0.030642
Init_Win_bytes_backward             -0.000660                 0.010016
act_data_pkt_fwd                     0.882566                 0.407471
min_seg_size_forward                 0.000021                -0.001193
ActiveMean                           0.038853                 0.100416
ActiveStd                            0.006318                 0.102761
ActiveMax                            0.028465                 0.125756
ActiveMin                            0.041185                 0.067749
IdleMean                             0.001020                 0.020631
IdleStd                              0.000364                 0.026406
IdleMax                              0.001045                 0.024051
IdleMin                              0.000938                 0.016646

                         TotalLengthofBwdPackets  FwdPacketLengthMax  \
DestinationPort                        -0.003388            0.090989
FlowDuration                            0.015998            0.263401
TotalFwdPackets                         0.996993            0.009071
TotalBackwardPackets                    0.994430            0.008764
TotalLengthofFwdPackets                 0.353781            0.196242
TotalLengthofBwdPackets                 1.000000            0.006409
FwdPacketLengthMax                      0.006409            1.000000
FwdPacketLengthMin                     -0.002356           -0.004279
FwdPacketLengthMean                    -0.001661            0.888881
FwdPacketLengthStd                     -0.000685            0.968528
BwdPacketLengthMax                      0.021829            0.084652
BwdPacketLengthMin                     -0.004263           -0.141937
BwdPacketLengthMean                     0.020545            0.064390
BwdPacketLengthStd                      0.005771            0.066017
FlowBytes/s                             0.000529            0.036176
FlowPackets/s                          -0.001674           -0.055579
FlowIATMean                            -0.001636            0.064136
FlowIATStd                             -0.001482            0.147345
FlowIATMax                              0.000834            0.191981
FlowIATMin                             -0.000427           -0.015605
FwdIATTotal                             0.015683            0.259605
FwdIATMean                             -0.001521            0.078730
FwdIATStd                              -0.001021            0.216195
FwdIATMax                               0.000383            0.196060
FwdIATMin                              -0.000939           -0.029645
BwdIATTotal                             0.018959            0.291316
BwdIATMean                             -0.001304            0.061718
BwdIATStd                              -0.000655            0.264942
BwdIATMax                               0.001733            0.252646
BwdIATMin                              -0.000923           -0.028275
FwdPSHFlags                             0.001640            0.005640
FwdURGFlags                            -0.000043           -0.001721
FwdHeaderLength                         0.000751            0.000258
BwdHeaderLength                         0.013691            0.000599
FwdPackets/s                           -0.001557           -0.048591
BwdPackets/s                           -0.001012           -0.049361
MinPacketLength                        -0.004903           -0.145975
MaxPacketLength                         0.020710            0.379791
PacketLengthMean                        0.023301            0.330913
PacketLengthStd                         0.011029            0.342713
PacketLengthVariance                    0.005736            0.253159
FINFlagCount                           -0.000822           -0.002918
SYNFlagCount                            0.001640            0.005640
RSTFlagCount                            0.000120            0.017752
PSHFlagCount                            0.003796            0.225389
ACKFlagCount                            0.002338           -0.026994
URGFlagCount                           -0.002539            0.021436
CWEFlagCount                           -0.000043           -0.001721
ECEFlagCount                            0.000119            0.017733
Down/UpRatio                            0.002942           -0.051328
AveragePacketSize                       0.021152            0.322293
AvgFwdSegmentSize                      -0.001661            0.888881
AvgBwdSegmentSize                       0.020545            0.064390
FwdHeaderLength.1                       0.000751            0.000258
SubflowFwdPackets                       0.996993            0.009071
SubflowFwdBytes                         0.354261            0.196506
SubflowBwdPackets                       0.994430            0.008764
SubflowBwdBytes                         1.000000            0.006410
Init_Win_bytes_forward                  0.001239            0.156956
Init_Win_bytes_backward                -0.000759            0.016324
act_data_pkt_fwd                        0.883966            0.007342
min_seg_size_forward                    0.000020            0.000601
ActiveMean                              0.035881            0.120591
ActiveStd                               0.003404            0.088104
ActiveMax                               0.024741            0.138784
ActiveMin                               0.039005            0.102884
IdleMean                                0.000507            0.171741
IdleStd                                 0.000010            0.175465
IdleMax                                 0.000491            0.190272
IdleMin                                 0.000498            0.147625

                         FwdPacketLengthMin  FwdPacketLengthMean  \
DestinationPort                   -0.047160             0.136916
FlowDuration                      -0.115716             0.134033
TotalFwdPackets                   -0.003255            -0.000262
TotalBackwardPackets              -0.002834            -0.000617
TotalLengthofFwdPackets           -0.001737             0.185073
TotalLengthofBwdPackets           -0.002356            -0.001661
FwdPacketLengthMax                -0.004279             0.888881
FwdPacketLengthMin                 1.000000             0.244192
FwdPacketLengthMean                0.244192             1.000000
FwdPacketLengthStd                -0.078434             0.897588
BwdPacketLengthMax                -0.133181            -0.002546
BwdPacketLengthMin                 0.295922            -0.039138
BwdPacketLengthMean               -0.114000            -0.013289
BwdPacketLengthStd                -0.133825            -0.005559
FlowBytes/s                        0.002124             0.086471
FlowPackets/s                     -0.050639            -0.042206
FlowIATMean                       -0.021986             0.046442
FlowIATStd                        -0.058111             0.111752
FlowIATMax                        -0.083348             0.141758
FlowIATMin                         0.001905            -0.012052
FwdIATTotal                       -0.119510             0.130590
FwdIATMean                        -0.013762             0.064226
FwdIATStd                         -0.106362             0.163443
FwdIATMax                         -0.090040             0.145240
FwdIATMin                          0.041573            -0.011421
BwdIATTotal                       -0.081032             0.169119
BwdIATMean                         0.014559             0.059901
BwdIATStd                         -0.053888             0.232921
BwdIATMax                         -0.035554             0.223271
BwdIATMin                          0.038961            -0.009286
FwdPSHFlags                        0.095161             0.062250
FwdURGFlags                       -0.001778            -0.001828
FwdHeaderLength                   -0.000707            -0.000056
BwdHeaderLength                   -0.000675             0.000214
FwdPackets/s                      -0.048163            -0.035265
BwdPackets/s                      -0.025238            -0.045847
MinPacketLength                    0.444083            -0.006920
MaxPacketLength                   -0.115708             0.287440
PacketLengthMean                  -0.056603             0.297478
PacketLengthStd                   -0.102958             0.279416
PacketLengthVariance              -0.088948             0.211705
FINFlagCount                      -0.051949            -0.014951
SYNFlagCount                       0.095161             0.062250
RSTFlagCount                      -0.005208             0.012889
PSHFlagCount                      -0.203102             0.091308
ACKFlagCount                      -0.108116            -0.006499
URGFlagCount                       0.014869             0.049994
CWEFlagCount                      -0.001778            -0.001828
ECEFlagCount                      -0.004695             0.013001
Down/UpRatio                       0.293811             0.031136
AveragePacketSize                 -0.039397             0.299532
AvgFwdSegmentSize                  0.244192             1.000000
AvgBwdSegmentSize                 -0.114000            -0.013289
FwdHeaderLength.1                 -0.000707            -0.000056
SubflowFwdPackets                 -0.003255            -0.000262
SubflowFwdBytes                   -0.001739             0.185317
SubflowBwdPackets                 -0.002834            -0.000617
SubflowBwdBytes                   -0.002356            -0.001661
Init_Win_bytes_forward            -0.147235             0.046666
Init_Win_bytes_backward           -0.070354            -0.014847
act_data_pkt_fwd                  -0.002303             0.000128
min_seg_size_forward              -0.001218             0.000117
ActiveMean                        -0.036253             0.090528
ActiveStd                         -0.033246             0.054109
ActiveMax                         -0.045621             0.090540
ActiveMin                         -0.028109             0.079015
IdleMean                          -0.078508             0.119915
IdleStd                           -0.032433             0.176961
IdleMax                           -0.080809             0.140576
IdleMin                           -0.074259             0.096046

                         FwdPacketLengthStd  BwdPacketLengthMax  \
DestinationPort                    0.123060           -0.212699
FlowDuration                       0.224957            0.485858
TotalFwdPackets                    0.001110            0.022552

In [ ]:
upper = corr_matrix.where(
    np.triu(np.ones(corr_matrix.shape), k=1).astype(bool)
)

# çiftleri al
corr_pairs = upper.stack()

# 0.9'dan büyük olanlar
high_corr = corr_pairs[abs(corr_pairs) > 0.99]

print(high_corr)

FlowDuration             FwdIATTotal                0.998529
TotalFwdPackets          TotalBackwardPackets       0.999070
                         TotalLengthofBwdPackets    0.996993
                         SubflowFwdPackets          1.000000
                         SubflowBwdPackets          0.999070
                         SubflowBwdBytes            0.996987
TotalBackwardPackets     TotalLengthofBwdPackets    0.994430
                         SubflowFwdPackets          0.999070
                         SubflowBwdPackets          1.000000
                         SubflowBwdBytes            0.994424
TotalLengthofFwdPackets  SubflowFwdBytes            0.999999
TotalLengthofBwdPackets  SubflowFwdPackets          0.996993
                         SubflowBwdPackets          0.994430
                         SubflowBwdBytes            1.000000
FwdPacketLengthMean      AvgFwdSegmentSize          1.000000
BwdPacketLengthMean      AvgBwdSegmentSize          1.000000
FlowIATMax               FwdIATMax                  0.998053
FwdPSHFlags              SYNFlagCount               1.000000
FwdURGFlags              CWEFlagCount               1.000000
FwdHeaderLength          FwdHeaderLength.1          1.000000
PacketLengthMean         AveragePacketSize          0.997822
RSTFlagCount             ECEFlagCount               0.997820
SubflowFwdPackets        SubflowBwdPackets          0.999070
                         SubflowBwdBytes            0.996987
SubflowBwdPackets        SubflowBwdBytes            0.994424
IdleMean                 IdleMax                    0.990238
                         IdleMin                    0.990080
dtype: float64

In [ ]:
df_final.to_csv("data_v1.csv", index=False)